Repository UNICEFECAR/USupport-components-library, pull requests merged in 2022-09, with the labels that each got.

#5 Automate components and component groups creation
  README.md
  create-component.bash
  src/components/examples/index.js
  src/components/icons/index.js
Labels: documentation, enhancement, patch, internal

#8 Development
  README.md
  src/components/icons/Icon/Icon.stories.jsx
  src/components/icons/assets/sprite.svg
  src/index.js
  styles.scss
Labels: patch

#10 Development
  .github/workflows/chromatic.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/components/icons/Icon/Icon.stories.jsx
  src/components/icons/assets/sprite.svg
  src/index.js
  styles.scss
Labels: enhancement

#11 Staging
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
Labels: patch, internal

#9 Feature/us 167 buttons
  create-component.bash
  package-lock.json
  package.json
  src/components/buttons/Button/Button.jsx
  src/components/buttons/Button/Button.stories.jsx
  src/components/buttons/Button/button.scss
  src/components/buttons/Button/index.js
  src/components/buttons/ButtonWithIcon/ButtonWithIcon.jsx
  src/components/buttons/ButtonWithIcon/ButtonWithIcon.stories.jsx
  src/components/buttons/ButtonWithIcon/buttonwithicon.scss
  src/components/buttons/ButtonWithIcon/index.js
  src/components/buttons/StoreButton/StoreButton.jsx
  src/components/buttons/StoreButton/StoreButton.stories.jsx
  src/components/buttons/StoreButton/index.js
  src/components/buttons/StoreButton/storebutton.scss
  src/components/buttons/index.js
  src/components/icons/Icon/Icon.jsx
  src/components/icons/Icon/icon.scss
  src/components/icons/assets/sprite.svg
  src/index.js
  src/styles/_variables.scss
Labels: enhancement
